### ISSUE TITLE
Using with docker-compose ?

### ISSUE THREAD

**Issue by GautierT** [joelgriffith/browserless#52]
Hi ! Thanks for this awesome docker image !
How to use with docker-compose ?

Here is my docker-compose.yml.
```
version: '3' # https://blog.codeship.com/using-docker-compose-for-nodejs-development/
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: app
    environment:
      - TIMBER=true
      - NODE_ENV=development
    command: node --inspect=0.0.0.0:3001 --require dotenv/config ./dist/index.js
    ports:
      - "8080:8080"
      - "9229:3001"
    links:
      - browserless
    depends_on:
      - browserless
  browserless:
    image: browserless/chrome:latest
    container_name: "browserless"
    environment:
      - DEBUG=browserless/chrome
      - MAX_CONCURRENT_SESSIONS=10
    ports:
        - 3002:3000
```
What should i put as url to connect to it with puppeteer ?
`app.locals.browser = await puppeteer.connect({browserWSEndpoint: 'ws://localhost:3002'})` doesn't work.

Thanks for your help !

**Comment by joelgriffith** [comment]
Out of curiosity, is there a load-balancer or Nginx in play? Your file looks good so might be something elsewhere.

Finally, what’s the response you’re seeing?

**Comment by GautierT** [comment]
Hi !
No Nginx and no load-balancer. It's in my local dev env. Using Docker for macOS.

Here is the output : 
```
Successfully built da5b4ac67a28
Successfully tagged app_dev:latest
Starting browserless ... done
Recreating lifebot-lettres-api_app_1 ... done
Attaching to browserless, lifebot-lettres-api_app_1
browserless    |
browserless    | > browserless-chrome@1.0.0-alpha start /usr/src/app
browserless    | > node ./build
browserless    |
app_1   | Debugger listening on ws://0.0.0.0:3001/0dad7a85-e454-4940-aa68-90d19424b33a
app_1   | For help see https://nodejs.org/en/docs/inspector
browserless    | Starting ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706) on port 9515
browserless    | Only local connections are allowed.
browserless    | [1535964089.005][SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)
browserless    | [1535964089.005][INFO]: listen on IPv6 failed with error ERR_ADDRESS_INVALID
app_1   | raven@2.6.3 alert: no DSN provided, error reporting disabled
app_1   | Creating ./tmp/ folder...
app_1   | process.env.NODE_ENV is :  development
app_1   | Connecting to MongoDb...
app_1   | [development] Connected to Database.
app_1   | Loading Routes...
app_1   | Starting Forest Admin...
app_1   | (node:1) Warning: N-API is an experimental feature and could change at any time.
app_1   | (node:1) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
app_1   | ex : Error: connect ECONNREFUSED 127.0.0.1:3003
app_1   | Find the server at : http://localhost:8080 in [development]
app_1   | Find the server at : http://localhost:8080 in [development]
```

**Comment by Tyga76** [comment]
hi, did you try ws://browserless:3002 ?? there will be an automatic DNS setup by Docker based on the service names in your compose.yml.

**Comment by joelgriffith** [comment]
Going to close this out due to inactivity, but feel free to keep the conversation going

**Comment by Jorgevillada** [comment]
@GautierT check this config.

```yaml
version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    env_file:
     - ./.env
    container_name: "browserless"
    ports:
      - "9090:9090"
    networks:
      - crawler4-network
  crawler4:
    env_file:
     - ./.env
    build: ./
    depends_on:
      - browserless
    links:
    #links to browserless container
      - "browserless:browserless"
    volumes: 
      - ~/.aws:/root/.aws
      - ./:/usr/src/app
    ports:
      - "3002:3000"
      - "3003:3001"
    networks:
      - crawler4-network
networks:
  crawler4-network:
```

.env file

```
DEBUG=browserless:*
MAX_CONCURRENT_SESSIONS=10
CONNECTION_TIMEOUT=60000
MAX_QUEUE_LENGTH=20
PREBOOT_CHROME=true
DEMO_MODE=false
HOST=0.0.0.0
ENABLE_DEBUGGER=false
TOKEN=a96a96b0-1234-11e8-a355-529269fb1459
PORT=9090
```

endpoint in crawler4

```
ws://browserless:9090?token=a96a96b0-1234-11e8-a355-529269fb1459
```
