### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by exentrich** [joelgriffith/browserless#99]
Please add healtcheck into docker container (or write about it in docs). I think it's good practice to do that. Docker itself in future version will have ability to restart unhealthy containers. For now we can use [Docker-Autoheal](https://github.com/willfarrell/docker-autoheal) to handle unhealthy restarts.

In my project i am using this simple **healthcheck.js** script for browserless:
```js
var http = require("http")

var options = {
    host : "127.0.0.1",
    port : "3000",
    timeout : 5000,
    path: '/pressure'
}

var request = http.request(options, (res) => {
    res.on("data", (chunk='')=>{
        if (chunk.indexOf('isAvailable":true')==-1){
            console.log('dead')
            process.exit(1)
        }
        else{
            console.log('healthy')
            process.exit(0)
        }
    })
})

request.on('error', function(err) {
    console.log(err.stack)
    process.exit(1);
})

request.end()
```

But i think you can make better solution.

In docker-compose.yml i added this rows:
```yml
healthcheck:
      test: ["CMD", "node", "/health.js"]
      interval: 30s
      timeout: 6s
      retries: 3
      start_period: 10s
volumes:
      - ./browserless/health.js:/health.js
```
